version: '3.8'

services:
  mysql:
    image: 'mysql:latest'
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=arian
    ports:
      - '3306:3306'
